'use strict';

// https://sqlite.org/lang_keywords.html
var keywords = {};
'ABORT ACTION ADD AFTER ALL ALTER ANALYZE AND AS ASC ATTACH AUTOINCREMENT BEFORE BEGIN BETWEEN BY CASCADE CASE CAST CHECK COLLATE COLUMN COMMIT CONFLICT CONSTRAINT CREATE CROSS CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP DATABASE DEFAULT DEFERRABLE DEFERRED DELETE DESC DETACH DISTINCT DROP EACH ELSE END ESCAPE EXCEPT EXCLUSIVE EXISTS EXPLAIN FAIL FOR FOREIGN FROM FULL GLOB GROUP HAVING IF IGNORE IMMEDIATE IN INDEX INDEXED INITIALLY INNER INSERT INSTEAD INTERSECT INTO IS ISNULL JOIN KEY LEFT LIKE LIMIT MATCH NATURAL NO NOT NOTNULL NULL OF OFFSET ON OR ORDER OUTER PLAN PRAGMA PRIMARY QUERY RAISE RECURSIVE REFERENCES REGEXP REINDEX RELEASE RENAME REPLACE RESTRICT RIGHT ROLLBACK ROW SAVEPOINT SELECT SET TABLE TEMP TEMPORARY THEN TO TRANSACTION TRIGGER UNION UNIQUE UPDATE USING VACUUM VALUES VIEW VIRTUAL WHEN WHERE WITH WITHOUT'
    .split(' ')
    .forEach(function (kw) { keywords[kw] = true });

var futureProof = {};
// keywords from sql92 that sqlite does not use
( 'ABSOLUTE ALLOCATE ANY ARE ASSERTION AT AUTHORIZATION AVG BIT BIT_LENGTH BOTH CASCADED CATALOG CHAR CHARACTER CHAR_LENGTH CHARACTER_LENGTH CLOSE COALESCE COLLATION CONNECT CONNECTION CONSTRAINTS CONTINUE CONVERT CORRESPONDING COUNT CURRENT CURRENT_USER CURSOR DATE DAY DEALLOCATE DEC DECIMAL DECLARE DESCRIBE DESCRIPTOR DIAGNOSTICS DISCONNECT DOMAIN DOUBLE END-EXEC EXCEPTION EXEC EXECUTE EXTERNAL EXTRACT FALSE FETCH FIRST FLOAT FOUND GET GLOBAL GO GOTO GRANT HOUR IDENTITY INDICATOR INPUT INSENSITIVE INT INTEGER INTERVAL ISOLATION LANGUAGE LAST LEADING LEVEL LOCAL LOWER MAX MIN MINUTE MODULE MONTH NAMES NATIONAL NCHAR NEXT NULLIF NUMERIC OCTET_LENGTH ONLY OPEN OPTION OUTPUT OVERLAPS PAD PARTIAL POSITION PRECISION PREPARE PRESERVE PRIOR PRIVILEGES PROCEDURE PUBLIC READ REAL RELATIVE REVOKE ROWS SCHEMA SCROLL SECOND SECTION SESSION SESSION_USER SIZE SMALLINT SOME SPACE SQL SQLCODE SQLERROR SQLSTATE SUBSTRING SUM SYSTEM_USER TIME TIMESTAMP TIMEZONE_HOUR TIMEZONE_MINUTE TRAILING TRANSLATE TRANSLATION TRIM TRUE UNKNOWN UPPER USAGE USER VALUE VARCHAR VARYING WHENEVER WORK WRITE YEAR ZONE'
+ ' '
// future proof keywords from sql92 that sqlite does not use
+ 'ALIAS ASYNC BOOLEAN BREADTH COMPLETION CALL CYCLE DATA DEPTH DICTIONARY ELSEIF EQUALS GENERAL LEAVE LESS LOOP MODIFY NEW NONE OBJECT OFF OID OLD OPERATION OPERATORS OTHERS PARAMETERS PENDANT PREORDER PRIVATE PROTECTED REF REFERENCING RESIGNAL RETURN RETURNS ROLE ROUTINE SEARCH SENSITIVE SEQUENCE SIGNAL SIMILAR SQLEXCEPTION SQLWARNING STRUCTURE TEST THERE TYPE UNDER VARIABLE VISIBLE WAIT WHILE'
).split(' ')
 .forEach(function(kw) { futureProof[kw] = true });

var sqlkeys = {};
sqlkeys.isKeyword = function (kw) { return keywords[kw] }
sqlkeys.isForFuture = function (kw) { return futureProof[kw] }
sqlkeys.isReserved = function (kw) { return keywords[kw] || futureProof[kw] }

module.exports = function (dialect) {
    return sqlkeys;
}
